name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-20.04
    # Write all permissions needed for 'release please' PR creation.
    permissions: write-all
    steps:
      # If the 'release please' action has been performed, we can actually
      # deploy the website.
      # Note: *every* step here needs to check the 'release_created' flag.
      - name: Checkout
        uses: actions/checkout@v3

      # Fixup Git URLs, see:
      # https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig

      # Install dependencies.
      - name: Install Dependencies
        run: npm install

      # Ensure that we can build the extension.
      - name: Build
        run: make build

      # Run all tests.
      - name: Test
        run: make test

      # Upload coverage.
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      # Create and verify the release.
      - name: Create and Verify Release
        run: |
          make release
          if [ -f ./release/chatgpt-diagrams-extension.zip ]; then
            echo "release exists..."
          else
            echo "cannot find release..."
            exit 1
          fi

      # Upload extension artifact.
      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v3
        with:
          name: chatgpt-diagrams-browser-extension
          path: ./release/chatgpt-diagrams-extension.zip

      # Run Release Please to create release pull requests if we have merged to
      # the main branch.
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: chatgpt-diagrams-extension

      # If we have created a release, attach the artifacts to it.
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./release/chatgpt-diagrams-extension.zip
